name: MortgageAnalytics
description: ''
version: 1.1.2
author: bobw@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: mortgageanalytics
  parentArtefactID: bobwprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-12 18:55:42'
pipelines:
  pipelines/mortgage_analytics:
    name: mortgage_analytics
    description: This codebase provides a mortgage analysis pipeline that processes
      data from two CSV files, MortgageEast.csv and MortgageWest.csv. The data is
      cleaned and merged, and then various calculations are performed to identify
      troubled mortgages. The troubled mortgages are then aggregated by state and
      sorted by the number of properties in trouble. Finally, the results are saved
      to a Delta table and a CSV file for further analysis and reporting.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-12 18:55:42'
    datasets:
      inputs:
      - datasets/mortgage_east_loandemo
      - datasets/mortgage_west_anya
      outputs:
      - datasets/csv_by_state_analysis_loandemo
      - datasets/tbl_all_mortgages
      - datasets/tbl_troubled_mortgages
    subgraphs: []
    dependencies: {}
  pipelines/troubled_mortgage_assistance:
    name: troubled_mortgage_HAF
    description: This codebase provides a mortgage assistance program that helps identify
      troubled mortgages in Nevada and provides assistance to customers. It reads
      in data from two sources, the `troubled_mortgages` table and the `MortgageCustomerNV.csv`
      file, and filters the customer data to only include those in Nevada. It then
      reformats the account number and joins the customer data with the mortgage data
      to create a comprehensive view of the customer's mortgage information. Finally,
      it writes the output to a CSV file named `mtg_assist_program.csv`. This program
      could be used by mortgage companies to identify and assist customers who are
      struggling with their mortgage payments.
    author: bobw@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-13 14:45:58'
    datasets:
      inputs:
      - datasets/customers_nv
      - datasets/customers_nv_loandemo
      - datasets/tar_troubled_mortgages
      - datasets/tbl_troubled_mortgages
      outputs:
      - datasets/mtg_assist_prog_HAF_csv_loandemo
      - datasets/myg_assist_program_csv
    subgraphs: []
    dependencies: {}
datasets:
  datasets/mortgage_east:
    name: mortgage_east
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 18:58:23'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 18:58:23'
  datasets/mortgage_west:
    name: mortgage_west
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 19:01:16'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 19:01:16'
  datasets/tar_all_mortgages:
    name: tar_all_mortgages
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:17:44'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:17:44'
  datasets/customers_nv:
    name: customers_nv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:37:42'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:37:42'
  datasets/state_analysis_csv:
    name: state_analysis_csv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:51:58'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:51:58'
  datasets/myg_assist_program_csv:
    name: myg_assist_program_csv
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-12 20:56:10'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: File
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-12 20:56:10'
  datasets/tar_troubled_mortgages:
    name: tar_troubled_mortgages
    description: ''
    author: bobw@prophecy.io
    createdAt: '2024-03-13 14:49:32'
    mode: batch
    physicalDatasets:
      Databricks-Prophecy:
        fabricId: 9631
        datasetType: Database
        description: ''
        author: bobw@prophecy.io
        createdAt: '2024-03-13 14:49:32'
  datasets/mortgage_east_loandemo:
    name: mortgage_east_loandemo
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:22:27'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:22:27'
  datasets/mortgage_west_anya:
    name: mortgage_west_anya
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:23:06'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:23:06'
  datasets/csv_by_state_analysis_anya:
    name: csv_by_state_analysis_anya
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:44:03'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:44:03'
  datasets/csv_by_state_analysis_loandemo:
    name: csv_by_state_analysis_loandemo
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:47:18'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: File
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:47:18'
  datasets/tbl_troubled_mortgages:
    name: tbl_troubled_mortgages
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:49:19'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:49:19'
  datasets/tbl_all_mortgages:
    name: tbl_all_mortgages
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 19:50:16'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 19:50:16'
  datasets/customers_nv_loandemo:
    name: customers_nv_loandemo
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 20:19:32'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: Database
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 20:19:32'
  datasets/mtg_assist_prog_HAF_csv_loandemo:
    name: mtg_assist_prog_HAF_csv_loandemo
    description: ''
    author: anya+webinar@prophecy.io
    createdAt: '2024-09-25 20:27:51'
    mode: batch
    physicalDatasets:
      devDatabricksAnya:
        fabricId: 183
        datasetType: File
        description: ''
        author: anya+webinar@prophecy.io
        createdAt: '2024-09-25 20:27:51'
templates: {}
jobs:
  jobs/job_MortgageAnalytics_DBX:
    name: job_MortgageAnalytics_DBX
    description: ''
    fabricUID: 9631
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/mortgage_analytics
    - pipelines/troubled_mortgage_assistance
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-03-13 18:48:01'
    author: bobw@prophecy.io
    models: []
    sqlProjects: []
  jobs/job_MortgageAnalytics_AF:
    name: job_MortgageAnalytics_AF
    description: ''
    fabricUID: 13760
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-03-13 18:49:09'
    author: bobw@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-12 18:55:42'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-06-04T18:31:55.787885Z'
  name: plibMaven
  version: 8.2.1
  id: '1686445435'
  createdAt: '2024-06-04T18:31:55.787786Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-09-25T13:17:51.080Z'
  name: ProphecyLibsPython
  version: 1.9.16
  id: '470973096'
  createdAt: '2024-06-04T18:31:55.787927Z'
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.30
    isDefault: true
    author: null
    createdAt: '2024-09-25 13:18:01'
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-06-11 03:39:34'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
